import turtle as t, time

def _():
    print("Initial Position: ", t.position())
    t.up()
    t.goto(-325, 275)
    t.color("black")
    t.fillcolor("black")
    t.begin_fill()
    t.down()
    t.forward(640)
    t.right(90)
    t.forward(540)
    t.right(90)
    t.forward(640)
    t.right(90)
    t.forward(540)
    t.right(90)
    t.end_fill()
def J():
    t.up()
    t.goto(-300, 100)
    t.down()
    t.color("blue")
    t.forward(100)
    t.backward(50)
    t.right(90)
    t.forward(150)
    t.right(45)
    for i in range(4):
        t.forward(25)
        t.right(45)

    print("Position J = ", t.position())
def A():
    t.up()
    t.goto(-175, -100)
    t.down()
    t.color("purple")
    t.left(45)
    t.forward(125)
    t.right(45)
    t.forward(50)
    t.right(90)
    t.forward(50)
    t.right(45)
    t.forward(25)
    t.right(90)
    t.forward(70.71)
    t.backward(70.71)
    t.left(90)
    t.forward(150)
    print("Position A = ", t.position())
def R():
    t.up()
    t.goto(-50, 100)
    t.down()
    t.color("cyan")
    t.forward(150)
    t.backward(75)
    t.left(45)
    t.forward(100)
    t.backward(100)
    t.left(45)
    for i in range(5):
        t.forward(31)
        t.left(45)
    print("Position R = ", t.position())
def V():
    t.up()
    t.goto(50, 50)
    t.down()
    t.color("green")
    t.right(135)
    t.backward(125)
    t.right(135)
    t.forward(50)
    t.left(90)
    t.forward(50)
    t.left(45)
    t.forward(125)
    print("Position V = ", t.position())
def I():
    t.up()
    t.goto(150, -75)
    t.down()
    t.color("white")
    t.forward(200)
    t.up()
    t.forward(20)
    t.down()
    t.left(45)
    for i in range(4):
        t.forward(15)
        t.right(90)
    print("Position I = ", t.position())
def S():
    t.up()
    t.goto(265, 50)
    t.down()
    t.color("magenta")
    t.forward(50)
    t.left(90)
    t.forward(50)
    t.left(45)
    t.forward(50)
    t.left(45)
    t.forward(25)
    t.left(45)
    t.forward(30)
    t.right(45)
    t.forward(25)
    t.right(45)
    t.forward(50)
    t.right(45)
    t.forward(50)
    t.right(90)
    t.forward(50)
    print("Position S = ", t.position())
def JARVIS():
    _()
    J()
    A()
    R()
    V()
    I()
    S()
    print("Jarvis: 'I have been summoned.'")
    time.sleep(5)

# JARVIS()

def shapeGenerator():
    print()
    print("Welcome to shape generator!")
    sides = input("How many sides: ")
    length = input("Insert side length(10-200): ")
    angle = input("Insert angle: ")
    color = input("Pick a color: ")
    b_color = input("Pick a background color: ")
    t.up()
    t.goto(-250, -250)
    t.left(90)
    t.down()
    t.fillcolor(b_color)
    t.begin_fill()
    for i in range(4):
        t.forward(500)
        t.right(90)
    t.end_fill()
    t.up()
    t.goto(-100,0)
    t.down()
    for i in range(int(sides)):
        t.color(color)
        t.forward(int(length))
        t.right(int(angle))
    time.sleep(5)


shapeGenerator()


